### PR TITLE
Update to current go and ability to use struct tags to specify name of the field

### PR DESCRIPTION
**Pull request by piranha**
In the second case it's the same as json decoder.

### CODE REVIEW

**Comment by sansolovyov** [comment]
Oops, I missed something, and did a bit of wrong stuff. Need to fix that. :)

**Comment by sansolovyov** [comment]
I don't know where I was looking, but now this is just update to current go. :)

**Comment by edsrzf** [comment]
LGTM, thanks. Feel free to add the ability to add the ability to specify key names in struct tags later if you want. :)

**Comment by sansolovyov** [comment]
Oh well, it's done by you already: https://github.com/edsrzf/tnetstring-go/blob/master/decode.go#L193

I did the same thing, but a bit earlier (a loop without checking a name) and then noticed that it's done. Not sure how have I missed that at all...

**Comment by edsrzf** [comment]
Oh, ok. It's been so long since I touched this I don't even remember what it does. :)

**Pull request merged**
